### ISSUE TITLE
Cannot add EAV attributes to a custom user model

### ISSUE THREAD

**Issue by pasiorovuo** [jazzband/django-eav2#41]
I have a custom user model according to instructions here [https://docs.djangoproject.com/en/2.1/topics/auth/customizing/](url) and would like to add user customisable attributes to the user model with django-eav2. In other areas of my project EAV attributes work as expected, but with custom user model (inherited from `django.contrib.auth.models.AbstractUser`) `python manage.py makemigrations users` fail with an error.

## Expected Behavior
`python manage.py makemigrations users` is successful and migration files are generated.

## Actual Behavior
`python manage.py makemigrations users` fails with following error and stacktrace:

```
(abstractusertest) pormb:abstractusertest por$ python manage.py makemigrations users
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/por/Projects/abstractusertest/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/por/Projects/abstractusertest/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Users/por/Projects/abstractusertest/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/por/Projects/abstractusertest/lib/python3.7/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/Users/por/Projects/abstractusertest/lib/python3.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/por/Projects/abstractusertest/abstractusertest/users/models.py", line 8, in <module>
    class User( django.contrib.auth.models.AbstractUser ):
  File "/Users/por/Projects/abstractusertest/lib/python3.7/site-packages/eav/decorators.py", line 21, in _model_eav_wrapper
    register(model_class, **kwargs)
  File "/Users/por/Projects/abstractusertest/lib/python3.7/site-packages/eav/__init__.py", line 5, in register
    Registry.register(model_cls, config_cls)
  File "/Users/por/Projects/abstractusertest/lib/python3.7/site-packages/eav/registry.py", line 70, in register
    reg._register_self()
  File "/Users/por/Projects/abstractusertest/lib/python3.7/site-packages/eav/registry.py", line 182, in _register_self
    self._attach_manager()
  File "/Users/por/Projects/abstractusertest/lib/python3.7/site-packages/eav/registry.py", line 111, in _attach_manager
    self.model_cls._meta.local_managers.remove(mgr)
ValueError: list.remove(x): x not in list
```
Additionally, if I enable EAV for User model, migrations of all other EAV'd models start failing with same error. If I remove traces of EAV from user model, other models work fine and EAV works fine.

## Steps to Reproduce
Test project attached
- Create a virtualenv (Python 3)
- Unpack attached file
- pip install -r requirements.txt
- python manage.py makemigrations users

## Your Environment
Mac OS X
Django==2.1.3
django-eav2==0.11.1

[abstractusertest.tar.gz](https://github.com/makimo/django-eav2/files/2584363/abstractusertest.tar.gz)

**Comment by IwoHerka** [comment]
Hi, thanks for the report. We will take a look at it.
